name: Database Sync - Production to Staging

on:
  schedule:
    # Run every day at 2 AM UTC (adjust timezone as needed)
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  sync-database:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Sync Production to Staging Database
      env:
        PRODUCTION_DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
        STAGING_DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
      run: |
        echo "🚀 Starting automated database sync..."
        node database-sync.js
        
    - name: Upload sync logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: database-sync-logs
        path: sync-logs/
        
    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ Database sync failed!"
        # Add notification logic here (email, Slack, etc.)
